# syntax=docker/dockerfile:1
FROM python:3.14

RUN apt-get update \
    && apt-get install -y gcc libpq-dev

RUN --mount=type=bind,source=requirements.txt,target=/tmp/requirements.txt \
    pip install -r /tmp/requirements.txt

COPY app.py /app/app.py

WORKDIR /app

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
