FROM python:3.14

COPY . /app/

RUN apt-get update \
    && apt-get install -y gcc libpq-dev

RUN pip install -r /app/requirements.txt

WORKDIR /app

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
